Add a day2 repetition slide
NETWAYS/gitlab-training pull request #164
Opened 2022-09-22 08:45 UTC by martialblog

Added before the workflow slides.

Tried a bullet point list, but it didn't fit on the page. Suggestions are welcome

Fixes #118

2022-09-22 10:40 UTC, theFeu commented
Currently at the wrong laptop and can't test it atm, @htriem can you hava a look?

2022-09-28 10:19 UTC, htriem requested changes
This looks good in principle - looking at the presenter mode, I'm not too sure about the font size though.
I'd be worried about showing this on a badly lit small screen. 

Is a side by side arragement possible, or can we have a higher contrast between the text and text background?

2022-09-28 11:55 UTC, theFeu commented
We can't really change anything about the style, since it's global for all trainings...

What we could do is split it on two slides, so we have 2 smaller rounds of exercises?

2022-09-28 13:49 UTC, theFeu commented
This should be a bit more readable, what do you think @martialblog @htriem ?

2022-09-28 14:09 UTC, martialblog commented
If we split it into two slides, then bullet points might fit on the pages. I just used the Code Block since the bullet points were spaced too wide

2022-09-29 08:48 UTC, theFeu commented
<img width="1218" alt="image" src="https://user-images.githubusercontent.com/22217062/192985616-7766d20a-87c1-41e5-9b50-c1daa60dca5e.png">

Fits well enough I suppose?

It doesn't look like you can group them together - which bothers me a little - but I can't think of anything better atm...

2022-09-29 10:08 UTC, martialblog commented on day2/00_Repetition/01_Intro.md
> +   * Switch to the master branch
TODO: change to `main`

2022-09-29 10:08 UTC, martialblog reviewed
I think the bullet points look better.

2022-09-29 10:09 UTC, martialblog commented
Maybe we can try a numbered list?

2022-09-29 12:40 UTC, theFeu commented
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/22217062/193033780-ad288351-2106-45f5-aa97-aeb5bdc23321.png">
 
I think this looks good

2022-09-29 12:45 UTC, theFeu commented
Okay, I am happy with this.
I think this can be squashed and merged

2022-09-29 13:18 UTC, martialblog reviewed
:+1: LGTM squash and merge

2022-09-29 13:45 UTC, merged