Release v4.0.0
NETWAYS/gitlab-training pull request #221
Opened 2023-04-12 14:22 UTC by martialblog

Major Refactor of the Training. 

Day 1:

- Smoother Start into Git core concepts
- Add more GitLab Topics on day1
- Add more GitLab Labs on day1
- Reword a lot of slides to be clearer
- Remove Create NMS GitLab Labs (as discussed)
- Move git tag to end of day and finish the day with a git tag v0.5 -m "End of Day One Release"

Day 2:

- Remove Integrations Chapter on day2, time will be used for more CI
- Optimize CI Chapter and add new CI Labs
- Streamline Git Workflow Examples
- Optimize rebase and squashing Slides
- Reword a lot of slides to be clearer
- Reword Git Workflow Slides and revert GitFlow images
- Add Release Pipeline Lab with Release v1.0 as "End of Training Release"

Fixes #209 

Fixes #220 

Fixes #200 

Fixes #217 

Fixes #214 

Fixes #199 

Fixes #216

2023-04-13 08:58 UTC, martialblog commented on showoff.json
> -  "author": "Feu Mourek, Henrik Triem, Markus Opolka, <br><small>originally Michael Friedrich</small>",
:+1:

2023-04-28 12:14 UTC, mocdaniel requested changes
Looks good, marked some typos here and there, will update the PR.

2023-04-28 12:14 UTC, mocdaniel commented on day1/06_Server/04_Connect_Local_Remote.md
> +Compare it with the local `git log` or `tig` entries.
```suggestion
Compare it to the local `git log` or `tig` entries.
```

2023-04-28 12:14 UTC, mocdaniel commented on day2/01_Workflows/04_Gitflow.md
> +Development happends on features branches.
```suggestion
Development happens on feature branches.
```

2023-04-28 12:14 UTC, mocdaniel commented on day2/01_Workflows/04_Gitflow.md
> +Development happends on features branches.
```suggestion
Development happens on feature branches.
```

2023-04-28 12:14 UTC, mocdaniel commented on day2/03_CI/01_Intro.md
> +Continuous integration (CI) is the practice to integrating new code more frequently and securely throughout the development.
```suggestion
Continuous integration (CI) is the practice of integrating new code more frequently and securely throughout development.
```

2023-04-28 12:14 UTC, mocdaniel commented on day2/03_CI/03_Gitlab_CI.md
> +The CI is configured by the `.gitlab-ci.yml` in our Git repository
```suggestion
The CI is configured by the `.gitlab-ci.yml` file in our Git repository
```

2023-04-28 12:14 UTC, mocdaniel commented on day2/03_CI/04_Gitlab_Pipelines.md
> +We can use the `rules` keyword include or exclude jobs.
```suggestion
We can use the `rules` keyword to include or exclude jobs.
```

2023-04-28 12:14 UTC, mocdaniel commented on day2/05_Outlook/31_LFS.md
> +* Git LFS is a plugin to overcome this shortcomming
```suggestion
* Git LFS is a plugin to overcome this shortcoming
```

2023-04-28 12:28 UTC, martialblog commented
Rebased/Squashed some commits. @theFeu also confirmed the PR.

Ship it :shipit:

2023-04-28 12:29 UTC, merged